name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: 'heimdal-7.8.0'

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: macos-14
            target: aarch64-apple-darwin
          - os: macos-13
            target: x86_64-apple-darwin
    permissions:
      contents: write
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: heimdal/heimdal
          ref: ${{ github.event.inputs.version }}
      - name: Install dependencies
        run: |
          cpan install JSON
          brew install autoconf
          brew install automake
          brew install libtool
          brew install texinfo
      - name: Build
        run: |
          ./autogen.sh
          ./configure -disable-shared --prefix=${{github.workspace}}/buildtools
          make
          make install
      - name: Compress build files
        run: |
          cp -f ${{github.workspace}}/lib/com_err/compile_et ${{github.workspace}}/buildtools/libexec/heimdal/
          cd ${{github.workspace}}/buildtools/libexec/heimdal/
          tar -czf asn1_compile_${{ matrix.platform.target }}.tar.gz asn1_compile compile_et
      - name: list files
        run: ls -al ${{github.workspace}}/buildtools/libexec/heimdal/
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{github.workspace}}/buildtools/libexec/heimdal/*.tar.gz
          tag: ${{ github.event.inputs.version }}
          overwrite: true
          file_glob: true
